# Generated by Django 2.2.4 on 2019-08-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyform',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='applyform',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='applyform',
            name='video_link',
            field=models.URLField(blank=True, null=True, verbose_name='Youtube Link'),
        ),
    ]
