# Generated by Django 2.2.3 on 2019-07-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='video_link',
            field=models.TextField(null=True),
        ),
    ]
