# Generated by Django 2.2.3 on 2019-07-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_auto_20190725_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['title'], 'verbose_name': 'photo', 'verbose_name_plural': 'photos'},
        ),
        migrations.AlterField(
            model_name='photo',
            name='video_link',
            field=models.URLField(null=True),
        ),
    ]
