# Generated by Django 2.2.3 on 2019-07-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_auto_20190725_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='photo',
            name='video_link',
            field=models.URLField(null=True, verbose_name='Youtube Link'),
        ),
    ]
