# Generated by Django 2.2.3 on 2019-08-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0008_auto_20190807_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='post_hit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
