# Generated by Django 2.2.3 on 2019-08-07 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0009_photo_post_hit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={},
        ),
    ]
